version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

sphinx:
  configuration: docs/conf.py

python:
  version: "3.8"
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
