name: Bug Report
description: Report an error
title: "[Bug] Replace with title"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        This form is for reporting bugs.

        If you have a question about how to use Locust, please: 
         * [Consult the documentation](https://docs.locust.io/en/stable/)
         * Search [Stack Overflow](https://stackoverflow.com/questions/tagged/locust), or [ask](https://stackoverflow.com/questions/ask there) yourself. If you tag it with "locust" we will see it
         * Ask on [Slack](https://locustio.slack.com) [(signup)](https://communityinviter.com/apps/locustio/locust)

        You can also ask new questions on  just remember to tag your question with "locust".

        Use this form only for reporting actual bugs in Locust.

        Remember, the developers of Locust are unpaid volunteers, so make sure you have tried everything you can think of before filing a bug :)

  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I have ensured that I'm using [the latest version of Locust](https://github.com/locustio/locust/releases/)
          required: true
        - label: I [searched for any existing report](https://github.com/locustio/locust/issues?q=is%3Aissue) about this bug to avoid making a duplicate.
          required: true
        - label: I am reporting a bug, not asking for general information or "how to do X in locust?"
          required: true

  - type: textarea
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of this bug, including the behaviour that you expected.
    validations:
      required: true

  - type: input
    attributes:
      label: Command line that you ran
      description: |
        For example: locust -f mylocustfile.py -t 10s --headless
    validations:
      required: true

  - type: textarea
    attributes:
      label: Locustfile contents
      render: python3
    validations:
      required: true

  - type: input
    attributes:
      label: Python version
    validations:
      required: true

  - type: input
    attributes:
      label: Locust version
    validations:
      required: true

  - type: input
    attributes:
      label: Operating system
    validations:
      required: true
