name: Bug Report
description: Report an error
title: "<put your title here>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        If your problem is more a question about how to use Locust, please: 
         * [Consult the documentation](https://docs.locust.io/en/stable/)
         * Search [Stack Overflow](https://stackoverflow.com/questions/tagged/locust), or [ask there](https://stackoverflow.com/questions/ask) yourself. If you tag it with `locust` we will see it.
         * Ask on [Slack](https://locustio.slack.com) [(signup)](https://communityinviter.com/apps/locustio/locust)

        Remember, the developers of Locust are unpaid volunteers, so make sure you have tried everything you can think of before filing a bug :)

  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
          required: true
        - label: This is really a bug, not a question
          required: true

  - type: textarea
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of this bug, including the behaviour that you expected.
    validations:
      required: true

  - type: input
    attributes:
      label: Command line that you ran
      description: |
        For example: locust -f mylocustfile.py -t 10s --headless
    validations:
      required: true

  - type: textarea
    attributes:
      label: Locustfile contents
      render: python3
    validations:
      required: true

  - type: input
    attributes:
      label: Python version
    validations:
      required: true

  - type: input
    attributes:
      label: Locust version
    validations:
      required: true

  - type: input
    attributes:
      label: Operating system
    validations:
      required: true
