blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://stackoverflow.com/questions/tagged/locust
    about: Check the FAQ in the wiki, and if there is no answer there, ask on StackOverflow
