name: "Tweet on release"
on:
  release:
    types: [published]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "New release: ${{ env.TAG }} https://github.com/locustio/locust/releases/tag/${{ env.TAG }}"
          consumer-key: ${{ secrets.TWITTER_API_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TWITTER_API_CONSUMER_SECRET }}
          access-token: ${{ secrets.TWITTER_API_ACCESS_TOKEN_KEY }}
          access-token-secret: ${{ secrets.TWITTER_API_ACCESS_TOKEN_SECRET }}
